"""changed referrer to user id

Revision ID: 2f80ec1ea60a
Revises: cf1e75773f20
Create Date: 2025-07-17 01:06:42.944789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2f80ec1ea60a"
down_revision: Union[str, Sequence[str], None] = "cf1e75773f20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "referred_by",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("users_referred_by_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "users", ["referred_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_referred_by_fkey"),
        "users",
        "users",
        ["referred_by"],
        ["telegram_id"],
    )
    op.alter_column(
        "users",
        "referred_by",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
