"""add language to user

Revision ID: 3cced56598b2
Revises: 41dc955560a4
Create Date: 2025-07-25 17:22:29.353360

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3cced56598b2"
down_revision: Union[str, Sequence[str], None] = "41dc955560a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "language", sa.Enum("EN", "RU", "UA", name="language", native_enum=False)
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language")
    # ### end Alembic commands ###
