"""added username to order, remove usd_price

Revision ID: cf1e75773f20
Revises: e474df0849d7
Create Date: 2025-07-17 00:59:52.800366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1e75773f20'
down_revision: Union[str, Sequence[str], None] = 'e474df0849d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('to_username', sa.String(), nullable=False))
    op.alter_column('users', 'referred_by',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_referred_by_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_referred_by_fkey'), 'users', 'users', ['referred_by'], ['id'])
    op.alter_column('users', 'referred_by',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('orders', 'to_username')
    # ### end Alembic commands ###
