"""Initial

Revision ID: e474df0849d7
Revises:
Create Date: 2025-07-11 05:41:01.883555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e474df0849d7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("reg_date", sa.DateTime(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("referred_by", sa.Integer(), nullable=True),
        sa.Column("referral_count", sa.Integer(), nullable=True),
        sa.Column("referral_balance", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column(
            "referral_total_earned", sa.Numeric(precision=18, scale=8), nullable=True
        ),
        sa.Column(
            "referral_commission", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["referred_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("stars_amount", sa.Integer(), nullable=True),
        sa.Column("price_ton", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("price_usd", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("price_usdt", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column(
            "payment_type", sa.Enum("TON", "USDT", name="paymenttype"), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "FAILED", "CANCELLED", name="orderstatus"),
            nullable=True,
        ),
        sa.Column("memo", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
