from dotenv import load_dotenv
import os

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
DATABASE_URL = os.getenv("DATABASE_URL")
FRAGMENT_API_KEY = os.getenv("FRAGMENT_API_KEY")
FRAGMENT_JWT_KEY = os.getenv("FRAGMENT_JWT_KEY")
TON_WALLET_ADDRESS = os.getenv("TON_WALLET_ADDRESS")
TON_WALLET_MNEMONIC = os.getenv("TON_WALLET_MNEMONIC")
TONCENTER_API_URL = os.getenv("TONCENTER_API_URL", "https://toncenter.com/api/v2")
TONCENTER_API_KEY = os.getenv("TONCENTER_API_KEY")
USDT_MASTER_ADDRESS = os.getenv(
    "USDT_MASTER_ADDRESS",
    "EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs",
)
USDT_TRANSFER_GAS_TON = os.getenv("USDT_TRANSFER_GAS_TON", "0.05")
HELEKET_API_KEY = os.getenv("HELEKET_API_KEY")
HELEKET_MERCHANT_ID = os.getenv("HELEKET_MERCHANT_ID")
HELEKET_WEBHOOK_URL = os.getenv("HELEKET_WEBHOOK_URL")
